### PR TITLE
Made the slideshow!

### PR DESCRIPTION
**Pull request by TheR3dErik**
There is now a slideshow on the page. You should probably check it over to make sure I didn't do anything drastically incorrect.

### CODE REVIEW

**Comment by JoshuaVSherman** [comment]
Great, I'll review it Tuesday

**Comment by chemmom2** [comment]
Yeah!!

**Comment by JoshuaVSherman** [comment]
Erik , please do the following and then push back to your branch and initiate a new pull request, thanks

git rm -r --cached node_modules
git commit -m 'Remove the now ignored directory node_modules'

**Comment by TheR3dErik** [comment]
ok, I will do this.

**Pull request closed without merging**
